### ISSUE TITLE
Logout command doesn't work

### ISSUE THREAD

**Issue by bradykelly** [bradykelly/chatnote#3]
_ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_command_error coro=<bound method Bot.on_command_error of <chatnotebot.bot.bot.Bot object at 0x000001BF8FEC95B0>> exception=TypeError('logout() takes 1 positional argument but 2 were given')>
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 338, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "D:\Personal\Python Projects\ChatNote\NoteBot\chatnotebot\bot\bot.py", line 109, in on_error
    await error.error(err, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "D:\Personal\Python Projects\ChatNote\NoteBot\chatnotebot\bot\bot.py", line 113, in on_command_error
    await error.command_error(ctx, exc)
  File "D:\Personal\Python Projects\ChatNote\NoteBot\chatnotebot\bot\cogs\error.py", line 126, in command_error
    raise original
  File "D:\ProgramData\Anaconda3\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Personal\Python Projects\ChatNote\NoteBot\chatnotebot\bot\cogs\control.py", line 52, in logout
    self.bot.logout(ctx)
TypeError: logout() takes 1 positional argument but 2 were given

**Comment by bradykelly** [comment]
Removed Control cog with faulty command
